### ISSUE TITLE
www.dropout.tv unsupported

### ISSUE THREAD

**Issue by schmuelio** [bdwinanto/sonarr_yt-dlp#1]
Config:
```yaml
sonarrytdl:
    scan_interval: 1
    debug: True
sonarr:
    host: sonarr
    port: 8989
    apikey: **********
    ssl: false
ytdl:
    default_format: bestvideo+bestaudio/best
series:
  - title: Dimension 20
    url: https://www.dropout.tv/dimension-20
    subtitles:
      languages: ['en.*']
    cookies_file: cookies.txt
```

Attempting to download a series from dropout.tv (which is supported by yt-dlp) causes the following error:

```
2022-01-16 14:00:34,891 - sonarr_youtubedl - INFO -   Dimension 20:
2022-01-16 14:00:34,892 - sonarr_youtubedl - DEBUG -   Cookies file used: /config/cookies.txt
2022-01-16 14:00:34,893 - sonarr_youtubedl - DEBUG - Youtube-DL opts used for episode matching
2022-01-16 14:00:34,894 - sonarr_youtubedl - DEBUG - {'ignoreerrors': True, 'playlistreverse': True, 'matchtitle': 'THE\\ BEGINNING\\ BEGINS', 'quiet': False, 'logger': <utils.YoutubeDLLogger object at 0x7fac6f417cd0>, 'progress_hooks': [<function ytdl_hooks at 0x7fac6f43f130>], 'cookie': '/config/cookies.txt'}
2022-01-16 14:00:35,664 - sonarr_youtubedl - DEBUG - [generic] dimension-20: Requesting header
2022-01-16 14:00:36,379 - sonarr_youtubedl - INFO - [generic] Falling back on generic information extractor.
2022-01-16 14:00:36,381 - sonarr_youtubedl - DEBUG - [generic] dimension-20: Downloading webpage
2022-01-16 14:00:37,002 - sonarr_youtubedl - DEBUG - [generic] dimension-20: Extracting information
2022-01-16 14:00:37,267 - sonarr_youtubedl - ERROR - ERROR: Unsupported URL: https://www.dropout.tv/dimension-20
Traceback (most recent call last):
  File "/app/sonarr_youtubedl.py", line 421, in <module>
    main()
  File "/app/sonarr_youtubedl.py", line 415, in main
    client.download(series, episodes)
  File "/app/sonarr_youtubedl.py", line 343, in download
    found, dlurl = self.ytsearch(ydleps, url)
  File "/app/sonarr_youtubedl.py", line 316, in ytsearch
    if 'entries' in result and len(result['entries']) > 0:
TypeError: argument of type 'NoneType' is not iterable
```

The call to yt-dlp directly produces expected results:
```
~ -> yt-dlp https://www.dropout.tv/dimension-20 --username ***** --password *****
[DropoutSeason] dimension-20: Downloading webpage
[download] Downloading playlist: Dimension 20 - Fantasy High
[DropoutSeason] playlist Dimension 20 - Fantasy High: Collected 20 videos; downloading 20 of them
[download] Downloading video 1 of 20
[Dropout] episode-1: Getting authenticity token
[Dropout] episode-1: Logging in
[Dropout] episode-1: Downloading video webpage
[Dropout] episode-1: Logging out
[vhx:embed] 320562: Downloading webpage
[vhx:embed] 320562: Downloading JSON metadata
[vhx:embed] 320562: Downloading akfire_interconnect_quic m3u8 information
WARNING: [vhx:embed] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[vhx:embed] 320562: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 320562: Downloading fastly_skyfire m3u8 information
[vhx:embed] 320562: Downloading fastly_skyfire m3u8 information
[vhx:embed] 320562: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 320562: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 320562: Downloading fastly_skyfire MPD information
[vhx:embed] 320562: Downloading fastly_skyfire MPD information
[info] 320562: Downloading 1 format(s): hls-fastly_skyfire-4707
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1139
[download] Destination: The Beginning Begins [320562].mp4
[download]   0.3% of ~3.82GiB at  4.31MiB/s ETA 07:19 (frag 3/1139)
```

**Comment by bdwinanto** [comment]
Please update yt-dlp in requirement.txt to 2021.12.27 then rebuild your image
Or pull latest image from bdwinanto/sonarr_yt-dlp

**Comment by schmuelio** [comment]
Thanks, that seems to have resolved the issue.
